# Generated by Django 3.0.3 on 2020-05-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_categoryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'категорії'},
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
