# Generated by Django 3.0.3 on 2020-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20200510_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/category', verbose_name='Зображення категорії'),
        ),
    ]
