# Generated by Django 3.0.3 on 2020-05-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20200514_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/items', verbose_name='Зображення виробу')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Category')),
            ],
        ),
    ]
