# Generated by Django 3.0.3 on 2020-05-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Вироби'},
        ),
    ]
