# Generated by Django 3.0.3 on 2020-05-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20200518_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default='qwe', max_length=100),
            preserve_default=False,
        ),
    ]
